### ISSUE TITLE
Configure what to open links with

### ISSUE THREAD

**Issue by wengole** [anthraxx/intellij-awesome-console#10]
I'm using this in PyCharm, and it's pretty handy, but if a traceback is shown in the console and the source isn't part of the project, it opens it with the OS default handler, which isn't PyCharm.

It would be nice to be able change this without resorting to changing the OS mime-type handler.

**Comment by anthraxx** [comment]
you should adjust your default editor for that mime type, we just use the normal intellij file opener to achieve this. That would be the proper way to define what should open your files :smile: 

I think we won't implement a custom opener with maybe even editor detection, that would be solving the issue the wrong way around. The reason for mime-type specific default handlers are exactly to handle such cases in a uniform way instead of every application doing something to make it open with something else you expect it to be
