### ISSUE TITLE
PyCharm 2020.1 Compatibility issue

### ISSUE THREAD

**Issue by eransevi** [anthraxx/intellij-awesome-console#57]
It's a great plugin, however with Pycharm CE version 2020.1, clicking a link in the console opens a text editor with the file instead of jumping to the correct source file in the IDE itself.
Maybe it's some configuration that should be fixed but I haven't found any way around it.

**Comment by anthraxx** [comment]
its related to you mime type configuration to handle specific file extensions automatically. The reason is as the kind of link you encounter gets interpreted as a "URL" based highlight which then is not handled by the internal file loader but by simple "open target" which then your systems configuration is responsible to.
If you paste the stacktrace I can check, however its still a good idea to configure your mime handling appropriately.
You can read about it here:
https://wiki.archlinux.org/index.php/default_applications
https://wiki.archlinux.org/index.php/XDG_MIME_Applications

**Comment by eransevi** [comment]
Thank you for your quick reply.
That was indeed the issue! 
The default app for .py files was vim, and setting it to Pycharm solved the issue.
It must have changed after some OS or PyCharm upgrade.
Again, great plugin and very useful.
