### ISSUE TITLE
"Seems" broken since a couple of intellij releases

### ISSUE THREAD

**Issue by djarnis73** [anthraxx/intellij-awesome-console#71]
### Issue ###
I know this is a very vague bug report, but since the last couple of updates I did to intellij, clicking on link in the console (for instance when doing Analyze Stack Trace) it does not navigate to the correct position in the java file.

When I disable the plugin it works again.

Sad because it is truly an awesome console.
### Environment ###
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16

**Comment by mahadi** [comment]
Same for me with PyCharm 2020.03
Jumps to the correct file but the line number is wrong

**Comment by astubbs** [comment]
Same for me with Java files. It is also consistent with the offset it is wrong by. This offset differs between files. 

I've disabled the plugin, and changed my logger to output the filename and line to match stack trace output - `(filename:line)` - this way Idea's native link system picks up the filename/line number link correctly (looks the same as a stack trace output). It wasn't working for me before because my output was `(filename:line#method)`.

Would ideally like to have the plugin enabled though :/
